# Generated by Django 4.0.5 on 2022-06-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
    ]
